name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.1.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm install --global npm@12.2.0
      - run: npm ci
      - run: npm run typecheck
      - run: npm test
      - run: npm run build
